### ISSUE TITLE
Create Jekyll Template

### ISSUE THREAD

**Issue by jermspeaks** [jermspeaks/jermspeaks.github.io#2]
## Objective

Create workable jekyll template to include all other pages
## Tasks
- [x] Configure Jekyll Settings
- [x] Create Boilerplate for Jekyll Site
- [x] Include About Page
- [x] Include Projects Page
- [ ] Include Social Media Links
- [x] Include Tinyletter Embed
- [ ] Include Personal Photo
- [ ] Include banner and large image assets
- [ ] Import Normalize.css
- [x] Add Own Base Styles

**Comment by jermspeaks** [comment]
Migrated away from Jekyll
